// Mock CJ products that mirror the real CJdropshipping catalog structure.
// Used when no CJ_API_KEY is configured in .env.local.
// Each product has 3-4 variants, real-looking images (Picsum), Saudi availability.

import type { CJProduct } from './cj-types';

const u = (seed: string) => `https://picsum.photos/seed/${seed}/800/800`;

const baseProducts: Array<Omit<CJProduct, 'inSaudiWarehouse'>> = [
  {
    id: 'CJ-1001',
    name: 'Car Phone Holder Mount Air Vent',
    sku: 'PH-2024-001',
    categoryId: 101,
    categoryName: 'Interior Accessories',
    brand: 'OEM',
    description: 'Universal car phone holder with gravity linkage, fits 4.7-7" screens. Strong grip, easy one-hand operation.',
    images: [u('cj1001-1'), u('cj1001-2'), u('cj1001-3'), u('cj1001-4')],
    weight: 120,
    length: 12,
    width: 8,
    height: 6,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 2.5, inventory: 5000, weight: 120 },
      { vid: 'v2', name: 'Silver', properties: 'Color:Silver', price: 2.7, inventory: 3200, weight: 120 },
    ],
    basePrice: 2.5,
    sourceUrl: 'https://detail.1688.com/offer/123.html',
  },
  {
    id: 'CJ-1002',
    name: 'MagSafe Wireless Car Charger 15W',
    sku: 'WC-MAG-15W',
    categoryId: 102,
    categoryName: 'Electronics',
    brand: 'Baseus',
    description: 'Strong N52 magnet wireless charging pad. 15W fast charge for iPhone 12+. 360° rotation.',
    images: [u('cj1002-1'), u('cj1002-2'), u('cj1002-3')],
    weight: 180,
    length: 10,
    width: 10,
    height: 8,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 8.9, inventory: 2200, weight: 180 },
      { vid: 'v2', name: 'White', properties: 'Color:White', price: 8.9, inventory: 1800, weight: 180 },
    ],
    basePrice: 8.9,
    sourceUrl: 'https://detail.1688.com/offer/456.html',
  },
  {
    id: 'CJ-1003',
    name: 'Oud Premium Car Air Freshener',
    sku: 'AF-OUD-001',
    categoryId: 103,
    categoryName: 'Fragrance',
    brand: 'Arabian Oud',
    description: 'Premium oud-scented car freshener. Lasts 60-90 days. Metal clip + wooden cap.',
    images: [u('cj1003-1'), u('cj1003-2'), u('cj1003-3'), u('cj1003-4')],
    weight: 35,
    length: 6,
    width: 3,
    height: 3,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Oud Royal', properties: 'Scent:Oud', price: 1.2, inventory: 12000, weight: 35 },
      { vid: 'v2', name: 'Musk White', properties: 'Scent:Musk', price: 1.2, inventory: 8500, weight: 35 },
      { vid: 'v3', name: 'Amber', properties: 'Scent:Amber', price: 1.2, inventory: 9200, weight: 35 },
    ],
    basePrice: 1.2,
    sourceUrl: 'https://detail.1688.com/offer/789.html',
  },
  {
    id: 'CJ-1004',
    name: 'Seat Gap Filler Organizer',
    sku: 'SGO-2024-001',
    categoryId: 104,
    categoryName: 'Interior Accessories',
    brand: 'OEM',
    description: 'PU leather seat gap organizer. Prevents phones, keys, coins from falling. Universal fit.',
    images: [u('cj1004-1'), u('cj1004-2'), u('cj1004-3')],
    weight: 80,
    length: 40,
    width: 8,
    height: 5,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 2.1, inventory: 7500, weight: 80 },
      { vid: 'v2', name: 'Beige', properties: 'Color:Beige', price: 2.1, inventory: 4300, weight: 80 },
      { vid: 'v3', name: 'Brown', properties: 'Color:Brown', price: 2.1, inventory: 3100, weight: 80 },
    ],
    basePrice: 2.1,
    sourceUrl: 'https://detail.1688.com/offer/abc.html',
  },
  {
    id: 'CJ-1005',
    name: '4K Dash Cam with Night Vision',
    sku: 'DC-4K-NV-001',
    categoryId: 105,
    categoryName: 'Electronics',
    brand: 'VIOFO',
    description: 'Sony IMX335 sensor, 4K 30fps, F1.8 aperture, GPS, WiFi, parking mode. 64GB included.',
    images: [u('cj1005-1'), u('cj1005-2'), u('cj1005-3'), u('cj1005-4')],
    weight: 320,
    length: 12,
    width: 6,
    height: 5,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Front Only', properties: 'Config:Front', price: 48, inventory: 1200, weight: 320 },
      { vid: 'v2', name: 'Front + Rear', properties: 'Config:Front+Rear', price: 65, inventory: 800, weight: 380 },
    ],
    basePrice: 48,
    sourceUrl: 'https://detail.1688.com/offer/def.html',
  },
  {
    id: 'CJ-1006',
    name: 'Backseat Organizer for Kids',
    sku: 'BSO-KID-001',
    categoryId: 106,
    categoryName: 'Family & Kids',
    brand: 'Disney',
    description: '6-pocket backseat organizer. Holds tablets, toys, snacks, bottles. Water-resistant.',
    images: [u('cj1006-1'), u('cj1006-2'), u('cj1006-3')],
    weight: 380,
    length: 60,
    width: 40,
    height: 2,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 5.8, inventory: 4200, weight: 380 },
      { vid: 'v2', name: 'Gray', properties: 'Color:Gray', price: 5.8, inventory: 3800, weight: 380 },
    ],
    basePrice: 5.8,
    sourceUrl: 'https://detail.1688.com/offer/ghi.html',
  },
  {
    id: 'CJ-1007',
    name: 'Portable Tire Inflator 12V',
    sku: 'TI-PORT-001',
    categoryId: 107,
    categoryName: 'Tools',
    brand: 'Baseus',
    description: '150 PSI max. Auto-shutoff. LED light. 3 nozzle adapters. Rechargeable 2000mAh.',
    images: [u('cj1007-1'), u('cj1007-2'), u('cj1007-3')],
    weight: 850,
    length: 18,
    width: 8,
    height: 22,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Standard', properties: 'Model:Standard', price: 18.5, inventory: 2800, weight: 850 },
    ],
    basePrice: 18.5,
    sourceUrl: 'https://detail.1688.com/offer/jkl.html',
  },
  {
    id: 'CJ-1008',
    name: 'Dual USB-C 65W Car Charger',
    sku: 'CC-65W-001',
    categoryId: 108,
    categoryName: 'Electronics',
    brand: 'Anker',
    description: 'PD 3.0 + QC 4.0. Charges laptops, tablets, phones. Compact aluminum body.',
    images: [u('cj1008-1'), u('cj1008-2'), u('cj1008-3')],
    weight: 65,
    length: 7,
    width: 4,
    height: 4,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 6.2, inventory: 5500, weight: 65 },
      { vid: 'v2', name: 'Silver', properties: 'Color:Silver', price: 6.5, inventory: 4200, weight: 65 },
    ],
    basePrice: 6.2,
    sourceUrl: 'https://detail.1688.com/offer/mno.html',
  },
  {
    id: 'CJ-1009',
    name: 'LED Interior Strip Lights RGB',
    sku: 'LED-RGB-001',
    categoryId: 109,
    categoryName: 'Lighting',
    brand: 'Govee',
    description: '4×24" LED strips. App control. Music sync. 16M colors. Adhesive backing.',
    images: [u('cj1009-1'), u('cj1009-2'), u('cj1009-3'), u('cj1009-4')],
    weight: 220,
    length: 60,
    width: 6,
    height: 2,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: '4-Strip Kit', properties: 'Config:4Strip', price: 7.8, inventory: 3200, weight: 220 },
      { vid: 'v2', name: '6-Strip Kit', properties: 'Config:6Strip', price: 9.2, inventory: 2100, weight: 280 },
    ],
    basePrice: 7.8,
    sourceUrl: 'https://detail.1688.com/offer/pqr.html',
  },
  {
    id: 'CJ-1010',
    name: 'Foldable Sunshade 5-Layer',
    sku: 'SS-5L-001',
    categoryId: 110,
    categoryName: 'Sun Protection',
    brand: 'EcoNour',
    description: '5-layer UV protection. Folds to 30cm disc. Universal sedan/SUV fit.',
    images: [u('cj1010-1'), u('cj1010-2'), u('cj1010-3')],
    weight: 280,
    length: 70,
    width: 5,
    height: 5,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Sedan', properties: 'Fit:Sedan', price: 4.5, inventory: 6200, weight: 280 },
      { vid: 'v2', name: 'SUV', properties: 'Fit:SUV', price: 5.1, inventory: 4100, weight: 320 },
    ],
    basePrice: 4.5,
    sourceUrl: 'https://detail.1688.com/offer/stu.html',
  },
  {
    id: 'CJ-1011',
    name: 'LED Work Light Bar 60W',
    sku: 'WL-60W-001',
    categoryId: 111,
    categoryName: 'Lighting',
    brand: 'Nilight',
    description: '6000K spot+flood combo. IP67 waterproof. 200m range. Off-road SUV/truck use.',
    images: [u('cj1011-1'), u('cj1011-2'), u('cj1011-3')],
    weight: 1200,
    length: 60,
    width: 8,
    height: 8,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: '12 inch', properties: 'Size:12in', price: 22, inventory: 1500, weight: 1200 },
      { vid: 'v2', name: '20 inch', properties: 'Size:20in', price: 32, inventory: 1100, weight: 1800 },
    ],
    basePrice: 22,
    sourceUrl: 'https://detail.1688.com/offer/vwx.html',
  },
  {
    id: 'CJ-1012',
    name: 'Handheld Car Vacuum 15000Pa',
    sku: 'VAC-HH-001',
    categoryId: 112,
    categoryName: 'Cleaning',
    brand: 'Baseus',
    description: 'Cordless 15000Pa suction. 30 min runtime. HEPA filter. 4 nozzles.',
    images: [u('cj1012-1'), u('cj1012-2'), u('cj1012-3')],
    weight: 720,
    length: 28,
    width: 8,
    height: 10,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Standard', properties: 'Model:Standard', price: 19, inventory: 2400, weight: 720 },
    ],
    basePrice: 19,
    sourceUrl: 'https://detail.1688.com/offer/yza.html',
  },
  {
    id: 'CJ-1013',
    name: 'Steering Wheel Cover Leather',
    sku: 'SW-LTH-001',
    categoryId: 113,
    categoryName: 'Interior Accessories',
    brand: 'BELLEZZA',
    description: 'Genuine leather. Anti-slip. 4 sizes (S/M/L/XL). 8 colors.',
    images: [u('cj1013-1'), u('cj1013-2'), u('cj1013-3')],
    weight: 200,
    length: 38,
    width: 38,
    height: 5,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'S (37-38cm) Black', properties: 'Size:S;Color:Black', price: 6.5, inventory: 3200, weight: 200 },
      { vid: 'v2', name: 'M (38-39cm) Beige', properties: 'Size:M;Color:Beige', price: 6.5, inventory: 2800, weight: 200 },
      { vid: 'v3', name: 'L (39-40cm) Black', properties: 'Size:L;Color:Black', price: 6.8, inventory: 2100, weight: 210 },
    ],
    basePrice: 6.5,
    sourceUrl: 'https://detail.1688.com/offer/bcd.html',
  },
  {
    id: 'CJ-1014',
    name: 'Memory Foam Lumbar Cushion',
    sku: 'LC-MF-001',
    categoryId: 114,
    categoryName: 'Comfort',
    brand: 'Everlasting Comfort',
    description: '100% memory foam. Ergonomic support. Removable washable cover. 2 straps.',
    images: [u('cj1014-1'), u('cj1014-2'), u('cj1014-3')],
    weight: 600,
    length: 40,
    width: 30,
    height: 12,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 9.5, inventory: 3800, weight: 600 },
      { vid: 'v2', name: 'Gray', properties: 'Color:Gray', price: 9.5, inventory: 2600, weight: 600 },
    ],
    basePrice: 9.5,
    sourceUrl: 'https://detail.1688.com/offer/efg.html',
  },
  {
    id: 'CJ-1015',
    name: 'Arabic Calligraphy Rear Mirror Pendant',
    sku: 'RMP-ARB-001',
    categoryId: 115,
    categoryName: 'Decoration',
    brand: 'Handmade',
    description: 'Hand-carved wooden pendant. 7 designs: oud, hilal, star, geometric. 30cm string.',
    images: [u('cj1015-1'), u('cj1015-2'), u('cj1015-3'), u('cj1015-4')],
    weight: 25,
    length: 8,
    width: 4,
    height: 1,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Oud (عود)', properties: 'Design:Oud', price: 1.4, inventory: 9500, weight: 25 },
      { vid: 'v2', name: 'Hilal (هلال)', properties: 'Design:Hilal', price: 1.4, inventory: 8200, weight: 25 },
      { vid: 'v3', name: 'Star (نجمة)', properties: 'Design:Star', price: 1.4, inventory: 7100, weight: 25 },
    ],
    basePrice: 1.4,
    sourceUrl: 'https://detail.1688.com/offer/hij.html',
  },
  {
    id: 'CJ-1016',
    name: 'Collapsible Trunk Organizer',
    sku: 'TR-CL-001',
    categoryId: 116,
    categoryName: 'Storage',
    brand: 'Drive Auto',
    description: '3-compartment collapsible. 30kg capacity. Reinforced walls. 2 side pockets.',
    images: [u('cj1016-1'), u('cj1016-2'), u('cj1016-3')],
    weight: 1100,
    length: 50,
    width: 30,
    height: 25,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 12, inventory: 1500, weight: 1100 },
      { vid: 'v2', name: 'Gray', properties: 'Color:Gray', price: 12, inventory: 1200, weight: 1100 },
    ],
    basePrice: 12,
    sourceUrl: 'https://detail.1688.com/offer/klm.html',
  },
  {
    id: 'CJ-1017',
    name: 'Anti-Glare Rear View Mirror',
    sku: 'RV-AG-001',
    categoryId: 117,
    categoryName: 'Safety',
    brand: 'OEM',
    description: 'Wide-angle 180°. Anti-glare night mode. Easy clip-on. Universal.',
    images: [u('cj1017-1'), u('cj1017-2'), u('cj1017-3')],
    weight: 150,
    length: 25,
    width: 7,
    height: 5,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Standard', properties: 'Model:Standard', price: 3.8, inventory: 4800, weight: 150 },
    ],
    basePrice: 3.8,
    sourceUrl: 'https://detail.1688.com/offer/nop.html',
  },
  {
    id: 'CJ-1018',
    name: 'Ultrasonic Aroma Diffuser 200ml',
    sku: 'AD-ULT-001',
    categoryId: 118,
    categoryName: 'Fragrance',
    brand: 'InvoGoods',
    description: '7 LED colors. 200ml tank. 30-day runtime. USB-C. Auto-off.',
    images: [u('cj1018-1'), u('cj1018-2'), u('cj1018-3')],
    weight: 320,
    length: 12,
    width: 12,
    height: 16,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Wood Grain', properties: 'Color:Wood', price: 11, inventory: 2200, weight: 320 },
      { vid: 'v2', name: 'White', properties: 'Color:White', price: 11, inventory: 1800, weight: 320 },
    ],
    basePrice: 11,
    sourceUrl: 'https://detail.1688.com/offer/qrs.html',
  },
  {
    id: 'CJ-1019',
    name: 'Bento Cup Holder Tray',
    sku: 'CHT-BEN-001',
    categoryId: 119,
    categoryName: 'Interior Accessories',
    brand: 'OEM',
    description: 'Anti-slip 3-section tray. Phone slot, cup holder, key pocket. 24×18cm.',
    images: [u('cj1019-1'), u('cj1019-2'), u('cj1019-3')],
    weight: 180,
    length: 24,
    width: 18,
    height: 3,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Beige', properties: 'Color:Beige', price: 3.2, inventory: 6200, weight: 180 },
      { vid: 'v2', name: 'Black', properties: 'Color:Black', price: 3.2, inventory: 5100, weight: 180 },
    ],
    basePrice: 3.2,
    sourceUrl: 'https://detail.1688.com/offer/tuv.html',
  },
  {
    id: 'CJ-1020',
    name: 'Smart Rear View Mirror 10.88"',
    sku: 'RV-SM-001',
    categoryId: 120,
    categoryName: 'Electronics',
    brand: 'Junsun',
    description: '4K front + 1080p rear cameras. 10.88" IPS touchscreen. GPS + WiFi + ADAS.',
    images: [u('cj1020-1'), u('cj1020-2'), u('cj1020-3'), u('cj1020-4')],
    weight: 720,
    length: 30,
    width: 8,
    height: 5,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: '32GB Bundle', properties: 'Storage:32GB', price: 52, inventory: 600, weight: 720 },
      { vid: 'v2', name: '64GB Bundle', properties: 'Storage:64GB', price: 58, inventory: 450, weight: 720 },
    ],
    basePrice: 52,
    sourceUrl: 'https://detail.1688.com/offer/wxy.html',
  },
  {
    id: 'CJ-1021',
    name: 'Steering Wheel Knob Spinner',
    sku: 'SW-KN-001',
    categoryId: 121,
    categoryName: 'Accessories',
    brand: 'OEM',
    description: 'Ball-bearing spinner knob. Power assist handle. Universal fit.',
    images: [u('cj1021-1'), u('cj1021-2'), u('cj1021-3')],
    weight: 80,
    length: 8,
    width: 6,
    height: 4,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 1.6, inventory: 6800, weight: 80 },
      { vid: 'v2', name: 'Red', properties: 'Color:Red', price: 1.6, inventory: 4200, weight: 80 },
    ],
    basePrice: 1.6,
    sourceUrl: 'https://detail.1688.com/offer/zab.html',
  },
  {
    id: 'CJ-1022',
    name: 'Car Trash Bin Collapsible',
    sku: 'TR-CN-001',
    categoryId: 122,
    categoryName: 'Interior Accessories',
    brand: 'OEM',
    description: 'Leak-proof collapsible bin. 4L capacity. Magnetic holder. Easy to clean.',
    images: [u('cj1022-1'), u('cj1022-2'), u('cj1022-3')],
    weight: 220,
    length: 18,
    width: 18,
    height: 8,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Black', properties: 'Color:Black', price: 2.9, inventory: 4800, weight: 220 },
    ],
    basePrice: 2.9,
    sourceUrl: 'https://detail.1688.com/offer/cde.html',
  },
  {
    id: 'CJ-1023',
    name: 'Premium Leather Key Chain',
    sku: 'KC-LTH-001',
    categoryId: 123,
    categoryName: 'Accessories',
    brand: 'Handmade',
    description: 'Genuine leather key chain. Steel ring. Arabic/English name engraving available.',
    images: [u('cj1023-1'), u('cj1023-2'), u('cj1023-3')],
    weight: 30,
    length: 10,
    width: 3,
    height: 1,
    isFreeShipping: true,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'Brown', properties: 'Color:Brown', price: 1.8, inventory: 5800, weight: 30 },
      { vid: 'v2', name: 'Black', properties: 'Color:Black', price: 1.8, inventory: 4900, weight: 30 },
    ],
    basePrice: 1.8,
    sourceUrl: 'https://detail.1688.com/offer/fgh.html',
  },
  {
    id: 'CJ-1024',
    name: 'Windshield Sun Cover XL',
    sku: 'SS-XL-001',
    categoryId: 124,
    categoryName: 'Sun Protection',
    brand: 'EcoNour',
    description: 'XL windshield cover. Fits sedans + SUVs. UV protection. Storage pouch included.',
    images: [u('cj1024-1'), u('cj1024-2'), u('cj1024-3')],
    weight: 350,
    length: 80,
    width: 5,
    height: 5,
    isFreeShipping: false,
    isInventoryWarning: false,
    variants: [
      { vid: 'v1', name: 'XL (Sedan/SUV)', properties: 'Size:XL', price: 5.8, inventory: 3500, weight: 350 },
    ],
    basePrice: 5.8,
    sourceUrl: 'https://detail.1688.com/offer/ijk.html',
  },
];

// mark some products as available in SA warehouse
const SA_WAREHOUSE_IDS = new Set([
  'CJ-1001','CJ-1002','CJ-1003','CJ-1004','CJ-1005','CJ-1006','CJ-1007',
  'CJ-1008','CJ-1009','CJ-1010','CJ-1012','CJ-1013','CJ-1014','CJ-1015',
  'CJ-1016','CJ-1017','CJ-1018','CJ-1019','CJ-1020','CJ-1021','CJ-1022',
  'CJ-1023','CJ-1024',
]);

export const mockCJProducts: CJProduct[] = baseProducts.map((p) => ({
  ...p,
  warehouse: SA_WAREHOUSE_IDS.has(p.id) ? 'SA' : 'CN',
  inSaudiWarehouse: SA_WAREHOUSE_IDS.has(p.id),
  shippingDaysToSA: SA_WAREHOUSE_IDS.has(p.id) ? 2 : 7,
}));

export const mockCJCategories = [
  { categoryId: 101, categoryName: 'Interior Accessories', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 102, categoryName: 'Electronics', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 103, categoryName: 'Fragrance', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 104, categoryName: 'Lighting', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 105, categoryName: 'Safety', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 106, categoryName: 'Sun Protection', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 107, categoryName: 'Tools', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 108, categoryName: 'Family & Kids', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 109, categoryName: 'Storage', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 110, categoryName: 'Comfort', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 111, categoryName: 'Cleaning', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 112, categoryName: 'Decoration', categoryLevel: 1, parentCategoryId: null },
  { categoryId: 113, categoryName: 'Accessories', categoryLevel: 1, parentCategoryId: null },
];
